project_name: xterrafile

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled

release:
  prerelease: auto
  draft: false
  github:
    owner: slillibri
    name: xterrafile

snapshot:
  name_template: "{{ .Version }}+next+{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

builds:
  - id: xterrafile
    main: ./main.go
    binary: xterrafile
    goos:
      - linux
      - darwin
      - freebsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

    ldflags:
      - -s -w
      - -X github.com/slillibri/xterrafile/cmd.version={{.Version}}
      - -X github.com/slillibri/xterrafile/cmd.commit={{.ShortCommit}}
      - -X github.com/slillibri/xterrafile/cmd.date={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Update README'
      - Merge pull request
      - Merge branch