name: CI

on:
  pull_request:
  push:

env:
  GO111MODULE: on

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Vendor modules
        run: go mod vendor
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v3.2.0

#  vet:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        if: success()
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.19.x
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Vendor modules
#        run: go mod vendor
#      - name: Run vet
#        run: go vet ./...
#
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        if: success()
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.19.x
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Vendor modules
#        run: go mod vendor
#      - name: Build binary
#        run: go build -o xterrafile main.go
#      - name: Run tests
#        run: go test -v -covermode=count ./...
#
#  coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        if: success()
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.19.x
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Vendor modules
#        run: go mod vendor
#      - name: Build binary
#        run: go build -o xterrafile main.go
#      - name: Calc coverage
#        run: |
#          go test -v -covermode=count -coverprofile=coverage.out ./...
#      - name: Convert coverage.out to coverage.lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.6
#      - name: Coveralls
#        uses: coverallsapp/github-action@v1.1.2
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage.lcov
